# Training 3

## Dictionary

In [13]:
dic = {}

In [14]:
dic['Canola'] = 45
dic['Wheat'] = 52
dic['Oat'] = 90

In [15]:
dic

{'Canola': 45, 'Wheat': 52, 'Oat': 90}

In [16]:
print(dic['Canola'])

45


In [19]:
print('Canola yield is', dic['Canola'])

Canola yield is 45


### Loops in Dictionary

In [23]:
for key, value in dic.items():
    print(key)
    print(value)

Canola
45
Wheat
52
Oat
90


In [26]:
dic_list = {
    'Canola': [35, 57, 60],
    'Whaet': [77, 53, 44]
}

In [27]:
dic_list

{'Canola': [35, 57, 60], 'Whaet': [77, 53, 44]}

## List Comprihentions

In [28]:
oats = [45, 44, 68, 79]

In [29]:
for i in oats:
    print(i)

45
44
68
79


In [38]:
oat_twice = []

for oat in oats:
    oat_twice.append(2*oat)

In [39]:
print(oat_twice)

[90, 88, 136, 158]


In [41]:
peas = [54, 64, 78, 99]

In [42]:
pea_square = []

for pea in peas:
    pea_square.append(pea**2)

In [43]:
print(pea_square)

[2916, 4096, 6084, 9801]


In [44]:
[2 * oat for oat in oats]

[90, 88, 136, 158]

In [45]:
[pea**2 for pea in peas]

[2916, 4096, 6084, 9801]

## NumPy

In [1]:
import numpy as np

In [2]:
array_1 = np.array([34,44,56])

In [3]:
array_1

array([34, 44, 56])

In [4]:
type(array_1)

numpy.ndarray

In [5]:
# Finding shape of array
array_1.shape

(3,)

In [6]:
array_2 = np.array([[45, 43, 56],
                    [67, 65, 66]])

In [7]:
array_2

array([[45, 43, 56],
       [67, 65, 66]])

In [9]:
array_2.shape

(2, 3)

In [24]:
# reshape()
array_2.reshape(6,)

array([45, 43, 56, 67, 65, 66])

In [17]:
# zeros()
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros( [3,4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
# ones
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones([3,4], dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
# arange()
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [32]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [33]:
# Indexing
array_2

array([[45, 43, 56],
       [67, 65, 66]])

In [35]:
array_2[0]

array([45, 43, 56])

In [36]:
array_2[1]

array([67, 65, 66])

In [39]:
array_2[:]

array([[45, 43, 56],
       [67, 65, 66]])

In [40]:
array_2[0,0]

45

In [42]:
array_2[0,1]

43

In [44]:
array_2[1,1]

65

In [45]:
# Math operations
array_2 * 2

array([[ 90,  86, 112],
       [134, 130, 132]])

In [46]:
array_2 - 20

array([[25, 23, 36],
       [47, 45, 46]])

In [47]:
array_2 + 45

array([[ 90,  88, 101],
       [112, 110, 111]])

In [48]:
array_2 / 23

array([[1.95652174, 1.86956522, 2.43478261],
       [2.91304348, 2.82608696, 2.86956522]])

In [50]:
array_2 ** 2

array([[2025, 1849, 3136],
       [4489, 4225, 4356]])

In [54]:
array_2

array([[45, 43, 56],
       [67, 65, 66]])

In [53]:
array_2 > 60

array([[False, False, False],
       [ True,  True,  True]])

In [55]:
array_2 < 60

array([[ True,  True,  True],
       [False, False, False]])

In [56]:
# Entire Matrix Agg
# Mean
np.mean(array_2)

57.0

In [57]:
# Standard Deviation
np.std(array_2)

9.882644720249063

In [58]:
# Variance
np.var(array_2)

97.66666666666667

In [61]:
# Median
np.median(array_2)

60.5

In [65]:
# Rows Agg
# Mean
np.mean(array_2, axis=1)

array([48., 66.])

In [73]:
# Columns Agg
# Mean
np.mean(array_2, axis=0)

array([56., 54., 61.])